### PR TITLE
Add support for specifying the config in a file, (partially) add resume token support

### PR DESCRIPTION
**Pull request by mbafford**
This is a ~90% PR, but I'm not going to have time to work on this for the rest of the week, so figured I'd get it in front of you to consider / comment on.

This adds support for loading settings from a config file using the module https://github.com/phha/click_config_file - it's a pretty decent module - it just loads each command line argument from the specified config file and falls back to normal behavior if no config file or the option is not specified in the config.

I also added support for reading (but not writing) the resume token and using that instead of the password. I couldn't find a good way in Click to make two options mutually exclusive - I wanted `token` to negate the need for `password`, but if neither was specified, then prompt for `password`.

The closest I found to an out-of-the-box solution was this module https://pypi.org/project/click-option-group/ - and some discussions from the project maintainer about how this type of thing was out of scope of the project, which doesn't make much sense to me.  Honestly, I got frustrated with trying to implement it and rolled my own that's good enough. 

If you have better ideas, please let me know.

Re resume token - I'm not sure:
- how long the resume token lasts for - I've been using the same one for two days now
- if it's any more secure than just storing an app password - the API implies it's still a full account access

I'm just thinking Google is less likely to lock an account that polls frequently as suspicious if it uses the token.

I think the program should probably save an updated token after every run, and I don't consider this really complete until that's done.

### CODE REVIEW

**Comment by ndbeals** [comment]
You are a beast!

Don't worry about the failed check, it's a broken github action. 

I'm still catching up on your earlier big PR/proposal (Does the [TODO here](https://github.com/ndbeals/keep-exporter/discussions/9#discussioncomment-304904) still apply? or does this PR cover much of it?)

**Comment by ndbeals** [comment]
About the resume token, I like the idea of using it, but I'm not sure where exactly to store it. `~/.config/keep-exporter/config.cfg` is an option. Or should there be no default path, and if the user wants to use the config file we can assume they are advanced enough to know to point to the file with `--config`?

The two main ways I see people using this is:

1. a once-off (or infrequent) run to archive or migrate from keep. In this case less setup is better, the `-u /-p` options or prompts are meant for this.
2. In a scheduled fashion. Config files or the environment variables are meant for this use.

**Comment by ndbeals** [comment]
The token is not any more or less secure than logging in with the password, it is for reducing the amount of authentications you need to make against Google keep. Your line about google locking the account is correct.

With that being said, updating the login token every time this is run is counter-productive to using the token login, and not possible (with token logins).

The login token is only changed when logged in via password. The token remains the same when you login with a token.

The most practical option is to have the tool fallback to password login if token login fails, and updating the token then. My reservations about that approach is the possibility of it messing up automation/cron jobs with false positives/silent failures.

**Comment by ndbeals** [comment]
This has worked nicely in my quick testing, merging it.

**Comment by mbafford** [comment]
> I'm still catching up on your earlier big PR/proposal (Does the [TODO here](https://github.com/ndbeals/keep-exporter/discussions/9#discussioncomment-304904) still apply? or does this PR cover much of it?)

I've edited this comment now and marked the ones I think no longer apply and left empty checkboxes for the ones I think do.

**Comment by ndbeals** [comment]
Cheers, thanks! My presences today will be diminished, I slipped a rib and can barely move my mousing arm.

I invited you as a collaborator, and the new work branch is `token-config`. There I'm refactoring exporting/login/cli logic to different files. As well as adding config file writing (for updating the token). And maybe check your email when you get a chance :)

**Comment by mbafford** [comment]
> The token is not any more or less secure than logging in with the password, it is for reducing the amount of authentications you need to make against Google keep. Your line about google locking the account is correct.
> The login token is only changed when logged in via password. The token remains the same when you login with a token.


Ok, I didn't verify the token behavior, was assuming it stored some state due to the name given by `gkeepapi` - "resume token" implies to me more than just log back in.

> The most practical option is to have the tool fallback to password login if token login fails, and updating the token then. My reservations about that approach is the possibility of it messing up automation/cron jobs with false positives/silent failures.

That depends on expiration of the token.  If it never expires, I'd prefer to only store the token in my config - assuming the token cannot be used for an interactive login attempt elsewhere, it's maybe slightly more secure to keep than the password. While the token does give full access, it's less convenient and less of an attack vector than a username + password sitting beside each other.

Ultimately, I would prefer neither but worry about neither (much) in my context - an environment of full trust and zero external access (hopefully!).

**Comment by mbafford** [comment]
> I slipped a rib and can barely move my mousing arm.

Yikes - I hope that's a quick recovery! Email received and appreciated will reply, but might be a couple of days.

Thanks for taking my stomping on your project so gracefully - you caught the full brunt of my weekend's hacking enthusiasm.

**Comment by ndbeals** [comment]
And thanks for the updated TODO, right off the bat I think I know the source of the unicode filename errors: `validate_path_string()`.

**Pull request merged**
